[project]
name = "autogen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "autogen-agentchat>=0.7.1",
    "autogen-core>=0.7.1",
    "autogen-ext[openai]>=0.7.1",
    "ipykernel>=6.30.0",
    "load-dotenv>=0.1.0",
]
